[tool.ruff]
line-length = 120
target-version = "py311"

# Enable Pyflakes, pycodestyle, and bugbear rules
select = ["E", "F", "B", "I", "D"]

# Exclude tests, cache directories, and build artifacts
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.per-file-ignores]
"tests/*" = ["D"]  # Ignore documentation-related rules in tests

[tool.ruff.pydocstyle]
convention = "google"  # Use Google-style docstrings

[tool.ruff.mccabe]
max-complexity = 10  # Set maximum cyclomatic complexity

[tool.ruff.pycodestyle]
max-line-length = 120  # Match line-length setting above