[theme]
# Professional dark theme with ESG-inspired color scheme
primaryColor = "#00C853"  # Green for ESG/sustainability
backgroundColor = "#0A1929"  # Dark blue-gray background
secondaryBackgroundColor = "#132F4C"  # Slightly lighter blue-gray
textColor = "#F8F9FA"  # Light gray text
font = "sans serif"  # Clean, modern font

[server]
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
